micronaut:
  application:
    name: my-app # Название вашего приложения
  server:
    port: 8080
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5434/news?reWriteBatchedInserts=true
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
    # Настройки пула (Hikari)
    maximum-pool-size: 10
    minimum-idle: 2

jpa:
  default:
    properties:
      hibernate:
        jdbc:
          batch_size: 50            # Размер пачки
          order_inserts: true       # Оптимизирует вставки
          order_updates: true       # Оптимизирует апдейты
        hbm2ddl:
          auto: update # Автоматическое создание/обновление таблиц (для дева)
        show_sql: true # Логирование SQL-запросов
        bytecode:
          provider: none
    entity-scan:
      - 'com.examine.entity'


# Настройки Jackson (JSON)
jackson:
  serialization:
    indent_output: true
    write_dates_as_timestamps: false

open-router:
  api-key:

qwen:
  header: Сделай краткое саммари (3-5 предложений) по статьям и верни JSON, в котором будем id и summary для каждого объекта\n\n
  request:  Сделай краткое саммари (3-5 предложений) по статье и верни JSON, в котором будем id = %s ; summary = %s